//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*
using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("autopartsModel", "productdb_ibfk_1", "producttypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(autopartsModel.producttype), "productdb", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(autopartsModel.productdb), true)]
[assembly: EdmRelationshipAttribute("autopartsModel", "cart_ibfk_1", "productdb", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(autopartsModel.productdb), "cart", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(autopartsModel.cart), true)]

#endregion

namespace autopartsModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class autopartsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new autopartsEntities object using the connection string found in the 'autopartsEntities' section of the application configuration file.
        /// </summary>
        public autopartsEntities() : base("name=autopartsEntities", "autopartsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new autopartsEntities object.
        /// </summary>
        public autopartsEntities(string connectionString) : base(connectionString, "autopartsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new autopartsEntities object.
        /// </summary>
        public autopartsEntities(EntityConnection connection) : base(connection, "autopartsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<productdb> productdbs
        {
            get
            {
                if ((_productdbs == null))
                {
                    _productdbs = base.CreateObjectSet<productdb>("productdbs");
                }
                return _productdbs;
            }
        }
        private ObjectSet<productdb> _productdbs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<producttype> producttypes
        {
            get
            {
                if ((_producttypes == null))
                {
                    _producttypes = base.CreateObjectSet<producttype>("producttypes");
                }
                return _producttypes;
            }
        }
        private ObjectSet<producttype> _producttypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<admin> admins
        {
            get
            {
                if ((_admins == null))
                {
                    _admins = base.CreateObjectSet<admin>("admins");
                }
                return _admins;
            }
        }
        private ObjectSet<admin> _admins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<guest> guests
        {
            get
            {
                if ((_guests == null))
                {
                    _guests = base.CreateObjectSet<guest>("guests");
                }
                return _guests;
            }
        }
        private ObjectSet<guest> _guests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<cart> carts
        {
            get
            {
                if ((_carts == null))
                {
                    _carts = base.CreateObjectSet<cart>("carts");
                }
                return _carts;
            }
        }
        private ObjectSet<cart> _carts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<warehouse> warehouses
        {
            get
            {
                if ((_warehouses == null))
                {
                    _warehouses = base.CreateObjectSet<warehouse>("warehouses");
                }
                return _warehouses;
            }
        }
        private ObjectSet<warehouse> _warehouses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the productdbs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproductdbs(productdb productdb)
        {
            base.AddObject("productdbs", productdb);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the producttypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducttypes(producttype producttype)
        {
            base.AddObject("producttypes", producttype);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the admins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadmins(admin admin)
        {
            base.AddObject("admins", admin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the guests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToguests(guest guest)
        {
            base.AddObject("guests", guest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the carts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocarts(cart cart)
        {
            base.AddObject("carts", cart);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the warehouses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowarehouses(warehouse warehouse)
        {
            base.AddObject("warehouses", warehouse);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="admin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class admin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new admin object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="shipping">Initial value of the shipping property.</param>
        /// <param name="handling">Initial value of the handling property.</param>
        /// <param name="localtax">Initial value of the localtax property.</param>
        public static admin Createadmin(global::System.Int32 id, global::System.Int32 shipping, global::System.Int32 handling, global::System.Int32 localtax)
        {
            admin admin = new admin();
            admin.id = id;
            admin.shipping = shipping;
            admin.handling = handling;
            admin.localtax = localtax;
            return admin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 shipping
        {
            get
            {
                return _shipping;
            }
            set
            {
                OnshippingChanging(value);
                ReportPropertyChanging("shipping");
                _shipping = StructuralObject.SetValidValue(value, "shipping");
                ReportPropertyChanged("shipping");
                OnshippingChanged();
            }
        }
        private global::System.Int32 _shipping;
        partial void OnshippingChanging(global::System.Int32 value);
        partial void OnshippingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 handling
        {
            get
            {
                return _handling;
            }
            set
            {
                OnhandlingChanging(value);
                ReportPropertyChanging("handling");
                _handling = StructuralObject.SetValidValue(value, "handling");
                ReportPropertyChanged("handling");
                OnhandlingChanged();
            }
        }
        private global::System.Int32 _handling;
        partial void OnhandlingChanging(global::System.Int32 value);
        partial void OnhandlingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 localtax
        {
            get
            {
                return _localtax;
            }
            set
            {
                OnlocaltaxChanging(value);
                ReportPropertyChanging("localtax");
                _localtax = StructuralObject.SetValidValue(value, "localtax");
                ReportPropertyChanged("localtax");
                OnlocaltaxChanged();
            }
        }
        private global::System.Int32 _localtax;
        partial void OnlocaltaxChanging(global::System.Int32 value);
        partial void OnlocaltaxChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="cart")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cart : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new cart object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="isInCart">Initial value of the isInCart property.</param>
        public static cart Createcart(global::System.Int32 id, global::System.String clientId, global::System.Int32 amount, global::System.Boolean isInCart)
        {
            cart cart = new cart();
            cart.id = id;
            cart.ClientId = clientId;
            cart.Amount = amount;
            cart.isInCart = isInCart;
            return cart;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value, false, "ClientId");
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.String _ClientId;
        partial void OnClientIdChanging(global::System.String value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value, "ProductId");
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductId;
        partial void OnProductIdChanging(Nullable<global::System.Int32> value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value, "Amount");
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Int32 _Amount;
        partial void OnAmountChanging(global::System.Int32 value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatePurchased
        {
            get
            {
                return _DatePurchased;
            }
            set
            {
                OnDatePurchasedChanging(value);
                ReportPropertyChanging("DatePurchased");
                _DatePurchased = StructuralObject.SetValidValue(value, "DatePurchased");
                ReportPropertyChanged("DatePurchased");
                OnDatePurchasedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatePurchased;
        partial void OnDatePurchasedChanging(Nullable<global::System.DateTime> value);
        partial void OnDatePurchasedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isInCart
        {
            get
            {
                return _isInCart;
            }
            set
            {
                OnisInCartChanging(value);
                ReportPropertyChanging("isInCart");
                _isInCart = StructuralObject.SetValidValue(value, "isInCart");
                ReportPropertyChanged("isInCart");
                OnisInCartChanged();
            }
        }
        private global::System.Boolean _isInCart;
        partial void OnisInCartChanging(global::System.Boolean value);
        partial void OnisInCartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authID
        {
            get
            {
                return _authID;
            }
            set
            {
                OnauthIDChanging(value);
                ReportPropertyChanging("authID");
                _authID = StructuralObject.SetValidValue(value, true, "authID");
                ReportPropertyChanged("authID");
                OnauthIDChanged();
            }
        }
        private global::System.String _authID;
        partial void OnauthIDChanging(global::System.String value);
        partial void OnauthIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String partName
        {
            get
            {
                return _partName;
            }
            set
            {
                OnpartNameChanging(value);
                ReportPropertyChanging("partName");
                _partName = StructuralObject.SetValidValue(value, true, "partName");
                ReportPropertyChanged("partName");
                OnpartNameChanged();
            }
        }
        private global::System.String _partName;
        partial void OnpartNameChanging(global::System.String value);
        partial void OnpartNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("autopartsModel", "cart_ibfk_1", "productdb")]
        public productdb productdb
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productdb>("autopartsModel.cart_ibfk_1", "productdb").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productdb>("autopartsModel.cart_ibfk_1", "productdb").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<productdb> productdbReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<productdb>("autopartsModel.cart_ibfk_1", "productdb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<productdb>("autopartsModel.cart_ibfk_1", "productdb", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="guest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class guest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new guest object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="shippingAddress">Initial value of the shippingAddress property.</param>
        public static guest Createguest(global::System.Int32 id, global::System.String name, global::System.String shippingAddress)
        {
            guest guest = new guest();
            guest.id = id;
            guest.name = name;
            guest.shippingAddress = shippingAddress;
            return guest;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String shippingAddress
        {
            get
            {
                return _shippingAddress;
            }
            set
            {
                OnshippingAddressChanging(value);
                ReportPropertyChanging("shippingAddress");
                _shippingAddress = StructuralObject.SetValidValue(value, false, "shippingAddress");
                ReportPropertyChanged("shippingAddress");
                OnshippingAddressChanged();
            }
        }
        private global::System.String _shippingAddress;
        partial void OnshippingAddressChanging(global::System.String value);
        partial void OnshippingAddressChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="productdb")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class productdb : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new productdb object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static productdb Createproductdb(global::System.Int32 id)
        {
            productdb productdb = new productdb();
            productdb.id = id;
            return productdb;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> typeId
        {
            get
            {
                return _typeId;
            }
            set
            {
                OntypeIdChanging(value);
                ReportPropertyChanging("typeId");
                _typeId = StructuralObject.SetValidValue(value, "typeId");
                ReportPropertyChanged("typeId");
                OntypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _typeId;
        partial void OntypeIdChanging(Nullable<global::System.Int32> value);
        partial void OntypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qty
        {
            get
            {
                return _qty;
            }
            set
            {
                OnqtyChanging(value);
                ReportPropertyChanging("qty");
                _qty = StructuralObject.SetValidValue(value, "qty");
                ReportPropertyChanged("qty");
                OnqtyChanged();
            }
        }
        private Nullable<global::System.Int32> _qty;
        partial void OnqtyChanging(Nullable<global::System.Int32> value);
        partial void OnqtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String image
        {
            get
            {
                return _image;
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true, "image");
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.String _image;
        partial void OnimageChanging(global::System.String value);
        partial void OnimageChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("autopartsModel", "productdb_ibfk_1", "producttypes")]
        public producttype producttype
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<producttype>("autopartsModel.productdb_ibfk_1", "producttypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<producttype>("autopartsModel.productdb_ibfk_1", "producttypes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<producttype> producttypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<producttype>("autopartsModel.productdb_ibfk_1", "producttypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<producttype>("autopartsModel.productdb_ibfk_1", "producttypes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("autopartsModel", "cart_ibfk_1", "cart")]
        public EntityCollection<cart> carts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cart>("autopartsModel.cart_ibfk_1", "cart");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cart>("autopartsModel.cart_ibfk_1", "cart", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="producttype")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class producttype : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new producttype object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static producttype Createproducttype(global::System.Int32 id)
        {
            producttype producttype = new producttype();
            producttype.id = id;
            return producttype;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("autopartsModel", "productdb_ibfk_1", "productdb")]
        public EntityCollection<productdb> productdbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<productdb>("autopartsModel.productdb_ibfk_1", "productdb");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<productdb>("autopartsModel.productdb_ibfk_1", "productdb", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="username">Initial value of the username property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static user Createuser(global::System.Int32 clientId, global::System.String username, global::System.String password)
        {
            user user = new user();
            user.ClientId = clientId;
            user.username = username;
            user.password = password;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    OnClientIdChanging(value);
                    ReportPropertyChanging("ClientId");
                    _ClientId = StructuralObject.SetValidValue(value, "ClientId");
                    ReportPropertyChanged("ClientId");
                    OnClientIdChanged();
                }
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false, "username");
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value, true, "number");
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private global::System.String _number;
        partial void OnnumberChanging(global::System.String value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="autopartsModel", Name="warehouse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class warehouse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new warehouse object.
        /// </summary>
        /// <param name="orderId">Initial value of the orderId property.</param>
        public static warehouse Createwarehouse(global::System.Int32 orderId)
        {
            warehouse warehouse = new warehouse();
            warehouse.orderId = orderId;
            return warehouse;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 orderId
        {
            get
            {
                return _orderId;
            }
            set
            {
                if (_orderId != value)
                {
                    OnorderIdChanging(value);
                    ReportPropertyChanging("orderId");
                    _orderId = StructuralObject.SetValidValue(value, "orderId");
                    ReportPropertyChanged("orderId");
                    OnorderIdChanged();
                }
            }
        }
        private global::System.Int32 _orderId;
        partial void OnorderIdChanging(global::System.Int32 value);
        partial void OnorderIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String paymentID
        {
            get
            {
                return _paymentID;
            }
            set
            {
                OnpaymentIDChanging(value);
                ReportPropertyChanging("paymentID");
                _paymentID = StructuralObject.SetValidValue(value, true, "paymentID");
                ReportPropertyChanged("paymentID");
                OnpaymentIDChanged();
            }
        }
        private global::System.String _paymentID;
        partial void OnpaymentIDChanging(global::System.String value);
        partial void OnpaymentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shippingAddress
        {
            get
            {
                return _shippingAddress;
            }
            set
            {
                OnshippingAddressChanging(value);
                ReportPropertyChanging("shippingAddress");
                _shippingAddress = StructuralObject.SetValidValue(value, true, "shippingAddress");
                ReportPropertyChanged("shippingAddress");
                OnshippingAddressChanged();
            }
        }
        private global::System.String _shippingAddress;
        partial void OnshippingAddressChanging(global::System.String value);
        partial void OnshippingAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String packagingStatus
        {
            get
            {
                return _packagingStatus;
            }
            set
            {
                OnpackagingStatusChanging(value);
                ReportPropertyChanging("packagingStatus");
                _packagingStatus = StructuralObject.SetValidValue(value, true, "packagingStatus");
                ReportPropertyChanged("packagingStatus");
                OnpackagingStatusChanged();
            }
        }
        private global::System.String _packagingStatus;
        partial void OnpackagingStatusChanging(global::System.String value);
        partial void OnpackagingStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShippingStatus
        {
            get
            {
                return _ShippingStatus;
            }
            set
            {
                OnShippingStatusChanging(value);
                ReportPropertyChanging("ShippingStatus");
                _ShippingStatus = StructuralObject.SetValidValue(value, true, "ShippingStatus");
                ReportPropertyChanged("ShippingStatus");
                OnShippingStatusChanged();
            }
        }
        private global::System.String _ShippingStatus;
        partial void OnShippingStatusChanging(global::System.String value);
        partial void OnShippingStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryStatus
        {
            get
            {
                return _DeliveryStatus;
            }
            set
            {
                OnDeliveryStatusChanging(value);
                ReportPropertyChanging("DeliveryStatus");
                _DeliveryStatus = StructuralObject.SetValidValue(value, true, "DeliveryStatus");
                ReportPropertyChanged("DeliveryStatus");
                OnDeliveryStatusChanged();
            }
        }
        private global::System.String _DeliveryStatus;
        partial void OnDeliveryStatusChanging(global::System.String value);
        partial void OnDeliveryStatusChanged();

        #endregion

    }

    #endregion

}
*/